// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RequestAccessibilityPermission() {
  return window['go']['main']['App']['RequestAccessibilityPermission']();
}

export function StartPipeline() {
  return window['go']['main']['App']['StartPipeline']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
