// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RequestAccessibilityPermission():Promise<void>;

export function StartPipeline():Promise<main.PasteResult>;

export function StopRecording():Promise<void>;
